/* Generated by tex3ds */
#pragma once

#define sheet_dialog_base_idx 0
#define sheet_dialog_baseMiddle_idx 1
#define sheet_dialog_button_idx 2
#define sheet_dialog_buttonMiddle_idx 3
#define sheet_dialog_buttonSplit_idx 4
#define sheet_dialog_waiticon_idx 5
#define sheet_dialog_waiticon_bg_idx 6
