/* Generated by tex3ds */
#pragma once

#define sheet_hud_generic_idx 0
#define sheet_hud_internet_idx 1
#define sheet_hud_cecman_idx 2
#define sheet_hud_local_idx 3
#define sheet_hud_noconnect_idx 4
#define sheet_hud_mask_bar_idx 5
#define sheet_hud_mask_cecwave_idx 6
#define sheet_hud_bar0_idx 7
#define sheet_hud_bar1_idx 8
#define sheet_hud_bar2_idx 9
#define sheet_hud_bar3_idx 10
#define sheet_hud_cecwave0_idx 11
#define sheet_hud_cecwave1_idx 12
#define sheet_hud_cecwave2_idx 13
#define sheet_hud_cecwave3_idx 14
#define sheet_hud_box_l_idx 15
#define sheet_hud_box_lf_idx 16
#define sheet_hud_box_le_idx 17
#define sheet_hud_box_m_idx 18
#define sheet_hud_box_mf_idx 19
#define sheet_hud_box_me_idx 20
#define sheet_hud_generic_bg_idx 21
#define sheet_hud_internet_bg_idx 22
#define sheet_hud_cecman_bg_idx 23
#define sheet_hud_local_bg_idx 24
#define sheet_hud_noconnect_bg_idx 25
#define sheet_hud_bar0_bg_idx 26
#define sheet_hud_bar1_bg_idx 27
#define sheet_hud_bar2_bg_idx 28
#define sheet_hud_bar3_bg_idx 29
#define sheet_hud_cecwave0_bg_idx 30
#define sheet_hud_cecwave1_bg_idx 31
#define sheet_hud_cecwave2_bg_idx 32
#define sheet_hud_cecwave3_bg_idx 33
